name: PHPUnitの実行
on: [ push ]
jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: website
          MYSQL_USER: posse
          MYSQL_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 環境の起動とテスト
        run: |
          docker-compose up -d
          cp src/.env.example src/.env
          docker-compose exec -T app sh composer install
          docker-compose exec -T app sh php artisan key:generate
          docker-compose exec -T app sh php artisan migrate --seed
          docker-compose exec -T app sh vendor/bin/phpunit